In [44]:
from collections import Counter
import numpy as np
from sklearn import datasets,neighbors
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [45]:
data = datasets.load_iris()

X = np.array(data["data"])
y = np.array(data["target"])
classes = data["target_names"]

print(X[:10])
print(np.unique(y),classes)
print(y[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
[0 1 2] ['setosa' 'versicolor' 'virginica']
[0 0 0 0 0 0 0 0 0 0]


In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, y)
data_train = zip(X_train, y_train)
data_train

In [47]:
def euclidean_distance(a, b):
    return np.linalg.norm(np.array(a) - np.array(b))

def classifier(data_train, classes, point, k=3):  
    # distance list
    distances = []
    for data_point in data_train:
        distance = euclidean_distance(data_point[0], point)   # distances from input-points to other points in training set
        distances.append((distance, data_point[1]))           # label of data-point
    
    distances = sorted(distances)[:k]     # Choosing 'k' points with the least distances.
    votes = [i[1] for i in distances]
    print(distances)
    print(votes)
    # Most commonly occurring class is the classification ouput
    result = Counter(votes).most_common(1)[0][0]
    return classes[result]
  


In [48]:
print("output: ",classifier(data_train, classes, [4.4, 3.1, 1.3, 1.4]))

[(1.1180339887498947, 0), (1.1618950038622249, 0), (1.1789826122551592, 0)]
[0, 0, 0]
output:  setosa


In [62]:
    ### Use SK-learn ###

clf = neighbors.KNeighborsClassifier(n_neighbors = 10, p = 2, weights = 'distance')  # 10 neighbors and norm 2
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Accuracy of KNN with 10 neighbors and major voting:" ,accuracy_score(y_test, y_pred))

output = clf.predict([[4.4, 3.1, 1.3, 1.4]])
print("output for above example: ", output, " => ", classes[output])

Accuracy of KNN with 10 neighbors and major voting: 1.0
output for above example:  [0]  =>  ['setosa']
