In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import sparse 
from sklearn.datasets import load_iris

In [2]:
# load data
x = load_iris().data
y = load_iris().target
N,d = x.shape
C = 3 # only for this data set
print(x.shape)
print(y.shape)

(150, 4)
(150,)


In [ ]:
def convert_labels(y, C = C):
    """
    convert 1d label to a matrix label: each column of this 
    matrix coresponding to 1 element in y. In i-th column of Y, 
    only one non-zeros element located in the y[i]-th position, 
    and = 1 ex: y = [0, 2, 1, 0], and 3 classes then return
            [[1, 0, 0, 1],
             [0, 0, 1, 0],
             [0, 1, 0, 0]]
    """
    Y = sparse.coo_matrix((np.ones_like(y), 
        (y, np.arange(len(y)))), shape = (C, len(y))).toarray()
    return Y 

y = convert_labels(y, C)
print(y.shape)
y

(3, 150)


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
# softmax:
def softmax(Z):
    for i in range(len(Z)):
      total = 0
      for j in range(C):
        total += np.exp(Z[i][j]) 
      for j in range(C):
        Z[i][j] = np.exp(Z[i][j]) / total
    return Z

In [ ]:
# Thêm cột 1 vào dữ liệu x
x = np.hstack((np.ones((N, 1)), x))
w = np.random.randn(d+1, C)
print(x.shape)
print(w)

(150, 5)
[[-0.54080095  0.51731727  0.50139623]
 [-1.89388897 -0.81552953 -0.91953122]
 [-1.07190377 -0.58817506 -0.38143499]
 [ 0.79713728 -0.64813521 -0.86828773]
 [ 0.43819507 -0.48993529 -1.28231956]]


In [ ]:
a = softmax(np.dot(x,w))
v=0
for i in range(C):
  v+= a[3][i]
  print(round(a[1][i],4))
print(v)
print((a.T - y).shape)
print(y * np.log(a.T))
# print(np.sum( (y * np.log(a.T)),axis=0 ))

0.0022
0.5906
0.4072
1.0
(3, 150)
[[-6.60201993 -6.11082575 -6.17149926 -5.7045708  -6.5560434  -6.42961726
  -5.9027986  -6.28808842 -5.53789645 -6.13994334 -6.8723604  -5.92818572
  -6.13330661 -6.0802884  -7.91941829 -7.32959967 -7.04193893 -6.47622925
  -6.80771916 -6.4933456  -6.39509065 -6.31184908 -6.76112404 -5.66189496
  -5.46895434 -5.90825235 -5.88692703 -6.55164883 -6.64823542 -5.71137036
  -5.75798279 -6.45425461 -7.02466518 -7.41667318 -6.01434952 -6.63483285
  -7.16896436 -6.58103827 -5.74801366 -6.3913841  -6.52622605 -5.33285021
  -5.86223991 -5.70049331 -5.75741863 -5.88322505 -6.46602471 -5.91478772
  -6.76907311 -6.38463536 -0.         -0.         -0.         -0.
  -0.         -0.         -0.         -0.         -0.         -0.
  -0.         -0.         -0.         -0.         -0.         -0.
  -0.         -0.         -0.         -0.         -0.         -0.
  -0.         -0.         -0.         -0.         -0.         -0.
  -0.         -0.         -0.         -0.   

In [ ]:
print(np.sum( (y * np.log(a.T)),axis=0 ))

[-6.60201993 -6.11082575 -6.17149926 -5.7045708  -6.5560434  -6.42961726
 -5.9027986  -6.28808842 -5.53789645 -6.13994334 -6.8723604  -5.92818572
 -6.13330661 -6.0802884  -7.91941829 -7.32959967 -7.04193893 -6.47622925
 -6.80771916 -6.4933456  -6.39509065 -6.31184908 -6.76112404 -5.66189496
 -5.46895434 -5.90825235 -5.88692703 -6.55164883 -6.64823542 -5.71137036
 -5.75798279 -6.45425461 -7.02466518 -7.41667318 -6.01434952 -6.63483285
 -7.16896436 -6.58103827 -5.74801366 -6.3913841  -6.52622605 -5.33285021
 -5.86223991 -5.70049331 -5.75741863 -5.88322505 -6.46602471 -5.91478772
 -6.76907311 -6.38463536 -0.21112133 -0.27037152 -0.2716986  -0.37876472
 -0.30013915 -0.44246047 -0.34458005 -0.31991749 -0.25888047 -0.40207616
 -0.35381845 -0.31045565 -0.26854736 -0.40504646 -0.25111422 -0.21191433
 -0.49257777 -0.29560886 -0.40125762 -0.30429378 -0.57862603 -0.24115211
 -0.49757671 -0.38258349 -0.23992001 -0.22718486 -0.2779522  -0.38753434
 -0.38104581 -0.24624448 -0.30737901 -0.28995461 -0

In [ ]:
plt.title('Cost Function J', size = 20)
plt.xlabel('No. of iterations', size=15)
plt.ylabel('Cost', size=15)
plt.plot(cost_list)
plt.show()

In [ ]:
N = 2 # number of training sample 
d = 2 # data dimension 
C = 3 # number of classes 

X = np.random.randn(d, N)
y = np.random.randint(0, 3, (N,))
print(X)
print(y)

[[-0.37622862  0.3862236 ]
 [ 0.25247402 -1.28125625]]
[2 0]
